import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const FILME_IDS = [
    "naruto_shippuden", "django_livre", "gladiador", "frozen", 
    "pulp_fiction_tempo_de_violencia", "one_piece", "vingadores_ultimato",
    "o_senhor_dos_aneis_a_sociedade_do_anel", "star_wars_uma_nova_esperanca",
    "o_labirinto_do_fauno", "liga_da_justica", "vinland_saga", 
    "hunter_x_hunter", "samurai_champloo", "parasyte", "the_umbrella_academy",
    "ilha_do_medo", "a_origem", "psicose", "death_note", 
    "scooby_doo_cade_voce", "you", "ozark", "true_detective", 
    "mindhunter", "gravity_falls_um_verao_de_misterios", "lost",
    "matrix", "cowboy_bebop", "interestelar", "de_volta_para_o_futuro", 
    "westworld", "stranger_things", "rick_and_morty", "e_t_o_extraterrestre", 
    "donnie_darko", "neon_genesis_evangelion", "steins_gate", "dr_stone", 
    "laboratorio_de_dexter", "final_space", "black_mirror", "dark", 
    "diarios_de_um_vampiro", "game_of_thrones", "the_witcher",
    "naruto", "naruto_the_last", "attack_on_titan", "black_clover", 
    "dragon_ball_z", "hora_de_aventura", "the_walking_dead", 
    "princess_mononoke", "my_hero_academia", "demon_slayer_kimetsu_no_yaiba", 
    "la_casa_de_papel", "jujutsu_kaisen", "fullmetal_alchemist_brotherhood", 
    "mob_psycho_100", "esquadrao_suicida", "code_geass_lelouch_of_the_rebellion", 
    "bleach", "the_boys", "batman_a_serie_animada", "yu_yu_hakusho",
    "as_meninas_superpoderosas", "samurai_jack", "pokemon",
    "forrest_gump_o_contador_de_historias", "clube_da_luta", "the_fragrant_flower",
    "o_poderoso_chefao", "violet_evergarden", "your_lie_in_april", 
    "a_lista_de_schindler", "orange", "cidade_de_deus", "o_show_de_truman", 
    "a_espera_de_um_milagre", "haikyu", "breaking_bad", "o_gambito_da_rainha", 
    "the_crown", "house_of_cards", "grey_s_anatomy", "euphoria", "titanic",
    "o_grande_hotel_budapeste", "friends", "irmao_do_jorel", "titio_avo", 
    "spy_x_family", "the_office_us", "one_punch_man", "kaguya_sama_love_is_war", 
    "clarencio_o_otimista", "apenas_um_show", "os_simpsons", "family_guy", 
    "south_park", "o_incrivel_mundo_de_gumball", "bob_esponja_calca_quadrada", 
    "du_dudu_e_edu", "pica_pau", "tom_e_jerry", "archer", "brooklyn_nine_nine",
    "bojack_horseman", "over_the_garden_wall", "steven_universe", 
    "noiva_cadaver", "o_silencio_dos_inocentes", "anabelle", "chainsaw_man", 
    "bastardos_inglorios", "dahmer_um_canibal_americano", "the_handmaids_tale", 
    "supernatural", "a_viagem_de_chihiro", "invocacao_do_mal", 
    "re_zero_starting_life_in_another_world", 
];

const COMENTARIOS_POR_FILME = {

naruto_the_last: [
    { nomeUsuario: "ShippudenFan", textoComentario: "Uma ótima ponte entre a série principal e Boruto. O foco no casal principal foi lindo!" },
    { nomeUsuario: "HinaLover", textoComentario: "Finalmente o desenvolvimento que a Hinata merecia. A cena da lua é memorável." },
    { nomeUsuario: "Tenseigan", textoComentario: "A animação está impecável! As lutas são muito bem coreografadas." },
    { nomeUsuario: "Kunoichi", textoComentario: "O filme tem um tom mais romântico, mas a ameaça global ainda funciona." },
    { nomeUsuario: "SextoHokage", textoComentario: "Assista, mas tenha em mente que é mais focado no romance do que na ação." },
],

frozen: [
    { nomeUsuario: "Ana&Elsa", textoComentario: "Um clássico moderno da Disney! As músicas são chicletes, no bom sentido." },
    { nomeUsuario: "Olaf_Melhor", textoComentario: "Olaf rouba a cena! 'Let It Go' é um hino que marcou uma geração." },
    { nomeUsuario: "ReinoDeArendelle", textoComentario: "A história sobre amor fraternal é muito mais forte do que a de romance clichê." },
    { nomeUsuario: "WinterWonder", textoComentario: "Visualmente deslumbrante, especialmente as cenas de gelo e neve." },
    { nomeUsuario: "PrincesaGelada", textoComentario: "Excelente reviravolta no vilão, fugindo do padrão dos contos de fadas." },
],

anabelle: [
    { nomeUsuario: "TerrorClassico", textoComentario: "O primeiro filme ainda é o melhor. A boneca é aterrorizante." },
    { nomeUsuario: "CinefiloDoMedo", textoComentario: "Construção de atmosfera e tensão são o ponto forte, menos nos sustos fáceis." },
    { nomeUsuario: "MundoInvocacao", textoComentario: "Adoro como ele se conecta ao universo de Invocação do Mal. Dá um bom contexto." },
    { nomeUsuario: "SemDormir", textoComentario: "A cena no porão me deixou sem fôlego. Medo real!" },
    { nomeUsuario: "MedrosoAnonimo", textoComentario: "Não é o terror mais original, mas cumpre o que promete: te fazer pular da cadeira." },
],

liga_da_justica: [
    { nomeUsuario: "DC_Fã", textoComentario: "A versão do Snyder (Snyder Cut) é a definitiva! Corrigiu todos os problemas da versão de cinema." },
    { nomeUsuario: "Super_Heroi", textoComentario: "Finalmente uma união épica! Ver o Batman e o Superman juntos vale a pena." },
    { nomeUsuario: "Flash_Veloz", textoComentario: "O Flash e o Aquaman dão o toque de alívio cômico que o filme precisava." },
    { nomeUsuario: "Cyborg_Power", textoComentario: "A história do Cyborg foi a que mais me emocionou, muito bem desenvolvida." },
    { nomeUsuario: "FilmeDeAcao", textoComentario: "Muita ação e bom drama. O Steppenwolf como vilão é decente." },
],

princess_mononoke: [
    { nomeUsuario: "GhibliLover", textoComentario: "Uma obra-prima atemporal. A mensagem sobre ecologia e guerra é profunda." },
    { nomeUsuario: "HayaoMestre", textoComentario: "Visualmente o filme é um espetáculo. A trilha sonora do Joe Hisaishi é perfeita." },
    { nomeUsuario: "Ashitaka", textoComentario: "Não há vilões e heróis simples, apenas personagens com motivações complexas. Isso é genial." },
    { nomeUsuario: "FantasiaÉpica", textoComentario: "A luta entre a humanidade e a natureza selvagem é de tirar o fôlego." },
    { nomeUsuario: "MelhorAnime", textoComentario: "Um dos filmes mais importantes do Studio Ghibli. Altamente recomendado." },
],

orange: [
    { nomeUsuario: "ShoujoFan", textoComentario: "Uma história tocante sobre amizade e depressão. Prepare os lenços!" },
    { nomeUsuario: "ViagemNoTempo", textoComentario: "A premissa das cartas do futuro é muito bem explorada e dramática." },
    { nomeUsuario: "GrupoDeAmigos", textoComentario: "O relacionamento dos amigos e o esforço deles para salvar Kakeru é lindo." },
    { nomeUsuario: "DramaRomance", textoComentario: "Foca bastante no desenvolvimento dos personagens e em como o passado afeta o presente." },
    { nomeUsuario: "FinalEmocionante", textoComentario: "Um dos animes mais sinceros e realistas sobre arrependimento e esperança." },
],

o_silencio_dos_inocentes: [
    { nomeUsuario: "SuspensePsico", textoComentario: "Um dos melhores thrillers psicológicos da história. Hannibal Lecter é icônico." },
    { nomeUsuario: "AgenteStarling", textoComentario: "Jodie Foster e Anthony Hopkins em atuações brilhantes. A tensão é palpável." },
    { nomeUsuario: "ClassicoCinema", textoComentario: "Um filme que te prende do início ao fim, sem enrolação. Roteiro impecável." },
    { nomeUsuario: "SerialKiller", textoComentario: "A dinâmica entre Clarice e Lecter é o cerne do filme. Fascinante e perturbador." },
    { nomeUsuario: "MelhorFilme", textoComentario: "Vencedor do 'Big Five' no Oscar por um bom motivo. Um filme obrigatório!" },
],

bastardos_inglorios: [
    { nomeUsuario: "TarantinoFan", textoComentario: "O diálogo de abertura no celeiro é uma obra-prima. Puro Tarantino." },
    { nomeUsuario: "CinefiloGuerra", textoComentario: "Uma visão estilizada e audaciosa da Segunda Guerra Mundial. Brad Pitt está hilário." },
    { nomeUsuario: "ChristophWaltz", textoComentario: "Hans Landa é um dos melhores vilões do cinema. Waltz merece todos os prêmios que ganhou." },
    { nomeUsuario: "HistoriaAlternativa", textoComentario: "Adorei a forma como a história é reescrita no final. Genial e divertido." },
    { nomeUsuario: "DialogoDeAcao", textoComentario: "Menos ação, mais tensão em cada palavra. O ritmo é perfeito." },
],

invocacao_do_mal: [
    { nomeUsuario: "CasalWarren", textoComentario: "O melhor universo de terror da atualidade. Ed e Lorraine Warren dão credibilidade." },
    { nomeUsuario: "Assustador", textoComentario: "Sustos bem construídos e uma atmosfera assustadora. A boneca é bizarra!" },
    { nomeUsuario: "FilmeDeTerror", textoComentario: "O primeiro filme é um clássico moderno. Manteve o terror em alta." },
    { nomeUsuario: "NoiteDeSustos", textoComentario: "Não dá para assistir sozinho. Recomendo para quem gosta de terror de possessão." },
    { nomeUsuario: "HistoriaReal", textoComentario: "O fato de ser baseado em fatos reais (supostamente) torna tudo mais tenso." },
],

invocacao_do_mal_3: [
    { nomeUsuario: "SequenciaBoa", textoComentario: "Não é tão bom quanto o primeiro, mas mantém o padrão de qualidade do universo." },
    { nomeUsuario: "NovosAres", textoComentario: "Gostei que eles mudaram o foco da casa mal-assombrada para um julgamento." },
    { nomeUsuario: "Julgamento", textoComentario: "O caso Arne Cheyenne Johnson é fascinante e foi bem adaptado." },
    { nomeUsuario: "CineTerror", textoComentario: "Muita ação e um pouco mais de 'thriller' que os anteriores. Bom entretenimento." },
    { nomeUsuario: "WarrenDeVolta", textoComentario: "Os atores continuam ótimos como Ed e Lorraine. O carisma deles sustenta o filme." },
],
naruto_shippuden: [
    { nomeUsuario: "EremitaDosSeisCaminhos", textoComentario: "O arco do Pain é, sem dúvida, o pico da série. A luta e a filosofia por trás dela são incríveis." },
    { nomeUsuario: "Time7", textoComentario: "A busca por Sasuke foi o que me manteve preso. É a parte mais emocionante e dramática da jornada." },
    { nomeUsuario: "MelhorAntagonista", textoComentario: "Itachi e Obito são os verdadeiros gênios do anime. As reviravoltas na história deles são impecáveis." },
    { nomeUsuario: "ShippudenRaiz", textoComentario: "A trilha sonora evoluiu demais! 'Sadness and Sorrow' na fase Shippuden é de arrepiar." },
    { nomeUsuario: "AnimeDaGuerra", textoComentario: "A Quarta Guerra Mundial Ninja teve seus altos e baixos, mas trouxe resoluções satisfatórias para quase todos os personagens." },
],
    naruto: [
        { nomeUsuario: "FãClássico", textoComentario: "Os arcos do Pain e da Guerra são insuperáveis! Sentirei falta desses personagens." },
        { nomeUsuario: "Hokage", textoComentario: "Anime maravilhoso! Shippuden marcou minha adolescência. O desenvolvimento do Naruto é incrível." },
        { nomeUsuario: "Sakura_Sama", textoComentario: "Muita enrolação às vezes, mas as lutas e o peso emocional são nota 10." },
        { nomeUsuario: "Uzumaki_Dono", textoComentario: "Preciso reassistir isso urgentemente. Um dos melhores shonen de todos os tempos." },
        { nomeUsuario: "Jiraya_Fan", textoComentario: "O final foi agridoce, mas o legado é eterno. Trilha sonora perfeita." },
    ],
    django_livre: [
        { nomeUsuario: "Cinema_Western", textoComentario: "Tarantino em sua melhor forma. O diálogo é ouro puro!" },
        { nomeUsuario: "DrSchultzFan", textoComentario: "Christoph Waltz rouba a cena. Que atuação impecável!" },
        { nomeUsuario: "Historico", textoComentario: "Uma abordagem forte e necessária de um período sombrio da história." },
        { nomeUsuario: "AmeiCandie", textoComentario: "A trilha sonora mesclando western e hip-hop é genial." },
        { nomeUsuario: "SkullCrush", textoComentario: "Cenas de ação muito bem coreografadas. Violência estilizada." },
    ],
    gladiador: [
        { nomeUsuario: "Roma_Eterna", textoComentario: "Um clássico moderno. Maximus é um dos maiores heróis do cinema." },
        { nomeUsuario: "Russell_Fan", textoComentario: "Russell Crowe fez o papel da vida dele. 'Vingança!' ⚔️" },
        { nomeUsuario: "HistoryBuff", textoComentario: "Visualmente impressionante, a reconstrução da Roma antiga é perfeita." },
        { nomeUsuario: "EpicMovie", textoComentario: "A cena da batalha inicial na floresta é icônica." },
        { nomeUsuario: "ComodusLover", textoComentario: "Joaquin Phoenix como Commodus é um vilão que amamos odiar." },
    ],
    frozen: [
        { nomeUsuario: "ElsaFrozen", textoComentario: "Minha filha ama! 'Let It Go' não sai da cabeça, haha." },
        { nomeUsuario: "AdultoFan", textoComentario: "A mensagem sobre o amor fraterno é linda e muito mais profunda que a de um 'príncipe'." },
        { nomeUsuario: "Olaf_Melhor", textoComentario: "Olaf é o alívio cômico que o filme precisava. Engraçadíssimo!" },
        { nomeUsuario: "DisneyFan", textoComentario: "Animação impecável. A neve parece real." },
        { nomeUsuario: "Musicais", textoComentario: "As músicas são cativantes, mas o primeiro é insuperável." },
    ],
    pulp_fiction_tempo_de_violencia: [
        { nomeUsuario: "TarantinoGod", textoComentario: "Diálogos memoráveis e uma narrativa não linear que revolucionou o cinema." },
        { nomeUsuario: "MiaWallace", textoComentario: "A cena da dança é um ícone cultural. Filmaço!" },
        { nomeUsuario: "JulesWinnfield", textoComentario: "A Bíblia de Ezequiel 25:17. Épico! Samuel L. Jackson está demais." },
        { nomeUsuario: "Filosofando", textoComentario: "Cada história se conecta de forma genial. Um quebra-cabeça perfeito." },
        { nomeUsuario: "ClássicoCult", textoComentario: "Assistir a este filme é obrigatório para qualquer cinéfilo." },
    ],
    one_piece: [
        { nomeUsuario: "Nakama_Sempre", textoComentario: "Melhor anime/mangá de todos. A construção de mundo e os laços de amizade são incríveis." },
        { nomeUsuario: "LuffyKing", textoComentario: "A saga de Wano está insana! O desenvolvimento do Zoro é demais." },
        { nomeUsuario: "ChoreiEmMarineford", textoComentario: "Nenhum shonen me fez chorar tanto quanto as histórias de One Piece." },
        { nomeUsuario: "Longão", textoComentario: "Sim, é longo, mas vale cada episódio. É uma jornada inesquecível." },
        { nomeUsuario: "DevilFruit", textoComentario: "O mistério das Akuma no Mi e do Século Perdido me deixa viciado!" },
    ],
    vingadores_ultimato: [
        { nomeUsuario: "MarvelManíaco", textoComentario: "O ápice de uma década de filmes. A batalha final é de arrepiar!" },
        { nomeUsuario: "Chorei", textoComentario: "A despedida do Homem de Ferro me pegou. Que momento épico." },
        { nomeUsuario: "Endgame", textoComentario: "O plot twist da viagem no tempo foi bem executado, apesar das complexidades." },
        { nomeUsuario: "CapitaoAmeric", textoComentario: "A cena 'Avengers, assemble' vale o ingresso!" },
        { nomeUsuario: "CinemaPipoca", textoComentario: "Um filme longo, mas cada minuto valeu a pena pela conclusão." },
    ],
    o_senhor_dos_aneis_a_sociedade_do_anel: [
        { nomeUsuario: "TolkienFan", textoComentario: "O início da jornada mais épica de todos os tempos. A Terra-média é mágica." },
        { nomeUsuario: "Frodo", textoComentario: "Os cenários são de tirar o fôlego. A ambientação é perfeita." },
        { nomeUsuario: "Gandalf", textoComentario: "'Não Passarás!' A ponte de Khazad-dûm é inesquecível." },
        { nomeUsuario: "CinemaFantasia", textoComentario: "Um marco do cinema de fantasia, difícil de ser superado." },
        { nomeUsuario: "MelhorTrilogia", textoComentario: "Um clássico que envelhece como vinho. Recomendo sempre!" },
    ],
    star_wars_uma_nova_esperanca: [
        { nomeUsuario: "JediMaster", textoComentario: "O filme que começou tudo. A jornada de Luke Skywalker é inspiradora." },
        { nomeUsuario: "OldSchool", textoComentario: "O charme dos efeitos especiais da época é imbatível. Clássico!" },
        { nomeUsuario: "HanSolo", textoComentario: "Han Solo e Chewbacca roubam a cena com seu carisma." },
        { nomeUsuario: "QueForça", textoComentario: "A Batalha de Yavin é a melhor sequência de combate espacial." },
        { nomeUsuario: "DarthVader", textoComentario: "Vader é o vilão mais icônico. Sua primeira aparição é poderosa." },
    ],
    o_labirinto_do_fauno: [
        { nomeUsuario: "DelToro", textoComentario: "Visceral e poético. Uma obra-prima que mistura fantasia e horror da guerra." },
        { nomeUsuario: "FantasiaSombria", textoComentario: "O Fauno é assustador, mas a Menina Pálida é o ápice do terror." },
        { nomeUsuario: "Chorei", textoComentario: "Uma história triste e linda sobre o escapismo da inocência." },
        { nomeUsuario: "Oscar", textoComentario: "A maquiagem e os efeitos práticos merecem todos os prêmios." },
        { nomeUsuario: "Espanhol", textoComentario: "Cinema espanhol de altíssima qualidade. Recomendo muito!" },
    ],
    liga_da_justica: [
        { nomeUsuario: "SnyderCut", textoComentario: "A versão de 4 horas é superior em todos os sentidos. Finalmente o filme que merecíamos." },
        { nomeUsuario: "Batman", textoComentario: "Ben Affleck é um Batman incrível. O melhor de todos." },
        { nomeUsuario: "Flash", textoComentario: "Ezra Miller é um alívio cômico na medida certa. O filme fica mais leve com ele." },
        { nomeUsuario: "DCFan", textoComentario: "É bom ver a união dos heróis, mesmo que o vilão seja fraco." },
        { nomeUsuario: "Esperança", textoComentario: "Ainda bem que o movimento dos fãs deu certo e o corte original foi lançado." },
    ],
    vinland_saga: [
        { nomeUsuario: "Thorfinn", textoComentario: "A evolução do Thorfinn é uma das mais profundas nos animes. 'Eu não tenho inimigos'." },
        { nomeUsuario: "AnimeViking", textoComentario: "Animação impecável e uma história viking que foca mais na paz do que na guerra." },
        { nomeUsuario: "Askeladd", textoComentario: "O melhor personagem da primeira temporada. Complexo e brilhante." },
        { nomeUsuario: "Filosofico", textoComentario: "Um anime que te faz refletir sobre o sentido da vida e da violência." },
        { nomeUsuario: "MAPPA", textoComentario: "O estúdio fez um trabalho lindo na segunda temporada, mantendo o nível." },
    ],
    hunter_x_hunter: [
        { nomeUsuario: "NenMaster", textoComentario: "O sistema de Nen é o melhor já criado em um shonen. Muita estratégia!" },
        { nomeUsuario: "ChimeraAnt", textoComentario: "O arco das Chimera Ants é um divisor de águas. Pesado e épico." },
        { nomeUsuario: "GonKillua", textoComentario: "A amizade de Gon e Killua é o coração do anime. Não tem como não amar." },
        { nomeUsuario: "Hisoka", textoComentario: "Um vilão caótico e divertido. Sua presença sempre eleva as lutas." },
        { nomeUsuario: "QueroMais", textoComentario: "Apesar dos hiatos, é uma obra-prima. Mal posso esperar pelo retorno." },
    ],
    samurai_champloo: [
        { nomeUsuario: "HipHopSamurai", textoComentario: "A trilha sonora é o que define essa obra. Uma fusão perfeita de hip-hop e Edo Japão." },
        { nomeUsuario: "Mugen", textoComentario: "Mugen é o melhor protagonista. Livre, caótico e cheio de estilo." },
        { nomeUsuario: "Fuu", textoComentario: "A jornada da Fuu para encontrar o samurai que cheira a girassóis é muito charmosa." },
        { nomeUsuario: "ShinichiroWatanabe", textoComentario: "O mesmo diretor de Cowboy Bebop. O estilo é inconfundível." },
        { nomeUsuario: "Fluidez", textoComentario: "As cenas de luta são fluidas e dinâmicas. Um anime subestimado." },
    ],
    parasyte: [
        { nomeUsuario: "Shinichi", textoComentario: "A relação de Shinichi e Migi é um desenvolvimento de personagem incrível." },
        { nomeUsuario: "TerrorCorpo", textoComentario: "Um anime de horror corporal bem feito. Algumas cenas são chocantes." },
        { nomeUsuario: "Migi", textoComentario: "Migi é o melhor parceiro. Irônico e lógico, ele rouba a cena." },
        { nomeUsuario: "Filosofia", textoComentario: "Explora o que significa ser humano e a sobrevivência das espécies. Profundo!" },
        { nomeUsuario: "Amei", textoComentario: "Um anime curto e direto, sem enrolação. Perfeito para maratonar." },
    ],
    the_umbrella_academy: [
        { nomeUsuario: "Luther", textoComentario: "A dinâmica familiar é o ponto forte. Cheio de personagens malucos." },
        { nomeUsuario: "Five", textoComentario: "O Five é o melhor personagem, com certeza. A atuação dele é impecável." },
        { nomeUsuario: "TrilhaSonora", textoComentario: "As coreografias de luta ao som de música pop são geniais. Sempre bem escolhidas." },
        { nomeUsuario: "Hargreeves", textoComentario: "O mistério do pai deles te prende do início ao fim." },
        { nomeUsuario: "Netflix", textoComentario: "Melhor série de super-heróis da Netflix, sem dúvida." },
    ],

    ilha_do_medo: [
        { nomeUsuario: "MisterioFan", textoComentario: "O final me deixou pensando por dias. Que reviravolta!" },
        { nomeUsuario: "Scorsese", textoComentario: "Direção incrível, a atmosfera é sufocante e o suspense psicológico é intenso." },
        { nomeUsuario: "LeoDiCaprio", textoComentario: "Melhor performance do Di Caprio em muito tempo. Injustiçado no Oscar." },
        { nomeUsuario: "Psicologia", textoComentario: "Excelente exploração da mente humana e do trauma. Não é só terror." },
        { nomeUsuario: "Twist", textoComentario: "A primeira vez que assisti, fui completamente enganado. 🤯" },
    ],
    a_origem: [
        { nomeUsuario: "Sonhos", textoComentario: "Uma obra-prima da ficção científica. A complexidade dos níveis de sonho é genial." },
        { nomeUsuario: "NolanFan", textoComentario: "Precisa de pelo menos duas assistidas para entender tudo. Fica melhor a cada vez." },
        { nomeUsuario: "AmeiTudo", textoComentario: "A trilha sonora (Time!) e os efeitos visuais são impressionantes até hoje." },
        { nomeUsuario: "Totem", textoComentario: "O pião rodando no final é o maior debate do cinema." },
        { nomeUsuario: "Ação", textoComentario: "A luta no corredor de gravidade zero é uma das melhores sequências de ação já feitas." },
    ],
    psicose: [
        { nomeUsuario: "Hitchcock", textoComentario: "A cena do chuveiro é a mais icônica da história do cinema. Puro suspense." },
        { nomeUsuario: "ClássicoP&B", textoComentario: "Um filme atemporal. A tensão é construída de forma magistral." },
        { nomeUsuario: "NormanBates", textoComentario: "Anthony Perkins é assustadoramente bom nesse papel. Vilão lendário." },
        { nomeUsuario: "TerrorPsicologico", textoComentario: "Não precisa de sangue para ser aterrorizante. O medo está na mente." },
        { nomeUsuario: "Inovador", textoComentario: "Revolucionou a forma como os filmes de suspense eram feitos." },
    ],
    death_note: [
        { nomeUsuario: "Kira", textoComentario: "Light Yagami é um dos anti-heróis mais inteligentes e assustadores dos animes." },
        { nomeUsuario: "L", textoComentario: "O duelo mental entre L e Light é a melhor parte. Pura estratégia." },
        { nomeUsuario: "Ryuk", textoComentario: "O Ryuk é hilário. Apenas observando a loucura humana comendo suas maçãs." },
        { nomeUsuario: "AnimeCrime", textoComentario: "Um suspense de crime perfeito. Difícil parar de assistir." },
        { nomeUsuario: "CadernoMaldito", textoComentario: "Se eu tivesse um Death Note..." },
    ],
    scooby_doo_cade_voce: [
        { nomeUsuario: "Nostalgia", textoComentario: "O desenho que marcou a infância. Amo a Máfia S.A.!" },
        { nomeUsuario: "VelmaDigna", textoComentario: "Velma é a verdadeira heroína, sempre resolvendo os mistérios com lógica." },
        { nomeUsuario: "CadêoScooby", textoComentario: "Sempre a mesma fórmula, e sempre funciona. Clássico atemporal." },
        { nomeUsuario: "Salsicha", textoComentario: "O Salsicha e o Scooby comendo sanduíches gigantes é meu momento favorito." },
        { nomeUsuario: "Desmascarado", textoComentario: "O mais legal é que nunca é um monstro de verdade, sempre um vigarista." },
    ],
    you: [
        { nomeUsuario: "JoeGoldberg", textoComentario: "Assustadoramente cativante. O Joe é um vilão que te faz questionar tudo." },
        { nomeUsuario: "Obsessão", textoComentario: "A série é um estudo sobre a obsessão e a fachada das redes sociais." },
        { nomeUsuario: "SuspenseNetflix", textoComentario: "A cada temporada, o Joe consegue se superar na loucura." },
        { nomeUsuario: "AmoOFelipe", textoComentario: "Quero saber o que o Joe vai aprontar agora. Viciante!" },
        { nomeUsuario: "Perigo", textoComentario: "É uma série que te deixa tenso do primeiro ao último episódio." },
    ],
    ozark: [
        { nomeUsuario: "MartyByrde", textoComentario: "Marty e Wendy são o casal mais problemático e fascinante da TV." },
        { nomeUsuario: "RuthLangmore", textoComentario: "Ruth é a alma da série! 'I don't know shit about fuck!' Lenda." },
        { nomeUsuario: "Crime", textoComentario: "Lavagem de dinheiro e drama familiar. Tensão do início ao fim." },
        { nomeUsuario: "Fotografia", textoComentario: "A fotografia escura e cinzenta combina perfeitamente com o clima da série." },
        { nomeUsuario: "Final", textoComentario: "Um dos finais mais polêmicos, mas que faz sentido para o arco da Wendy." },
    ],
    true_detective: [
        { nomeUsuario: "RustCohle", textoComentario: "A primeira temporada é uma obra-prima. McConaughey e Harrelson estão no auge." },
        { nomeUsuario: "FilosofiaNoir", textoComentario: "Diálogos existenciais profundos e uma atmosfera de mistério sufocante." },
        { nomeUsuario: "Temporada1", textoComentario: "Nenhuma outra temporada conseguiu superar a original. É um marco." },
        { nomeUsuario: "HBO", textoComentario: "Série com qualidade de cinema. O roteiro é extremamente bem escrito." },
        { nomeUsuario: "YellowKing", textoComentario: "O mistério do Rei Amarelo é o que prende a atenção. Impecável." },
    ],
    mindhunter: [
        { nomeUsuario: "BTK", textoComentario: "A parte mais assustadora são as entrevistas com serial killers reais." },
        { nomeUsuario: "DavidFincher", textoComentario: "Direção e estética impecáveis, o que se espera de Fincher." },
        { nomeUsuario: "Psicopatas", textoComentario: "Interessante ver o nascimento da ciência do perfil criminal." },
        { nomeUsuario: "EdKemper", textoComentario: "O ator que faz Kemper é idêntico! Arrepia só de olhar." },
        { nomeUsuario: "CadêaTemporada3", textoComentario: "Precisamos que a Netflix traga essa série de volta!" },
    ],
    gravity_falls_um_verao_de_misterios: [
        { nomeUsuario: "Dipper", textoComentario: "Melhor desenho animado de mistério. Os códigos e segredos escondidos são demais." },
        { nomeUsuario: "BillCipher", textoComentario: "O Bill Cipher é um vilão memorável e aterrorizante. Fofo e maligno." },
        { nomeUsuario: "Mabel", textoComentario: "A Mabel e suas gafes são hilárias. O contraste com o Dipper funciona muito." },
        { nomeUsuario: "PraTodaIdade", textoComentario: "Não é só para crianças. O roteiro é complexo e satisfaz adultos." },
        { nomeUsuario: "NostalgiaCN", textoComentario: "Um dos últimos grandes desenhos originais do Cartoon Network." },
    ],
    lost: [
        { nomeUsuario: "JackShephard", textoComentario: "Um fenômeno da TV. Cada episódio te deixava com mais perguntas." },
        { nomeUsuario: "Flashbacks", textoComentario: "A narrativa com flashbacks era inovadora e super envolvente." },
        { nomeUsuario: "FinalRuim", textoComentario: "O final é controverso, mas a jornada vale a pena. O mistério da ilha é ótimo." },
        { nomeUsuario: "TeamLocke", textoComentario: "John Locke é meu personagem favorito. A fé versus a ciência." },
        { nomeUsuario: "MelhorSérie", textoComentario: "A série que definiu a década de 2000. Clássico." },
    ],

    matrix: [
        { nomeUsuario: "RedPill", textoComentario: "Revolucionário! A forma como o filme mistura filosofia e ação é incrível." },
        { nomeUsuario: "BulletTime", textoComentario: "O efeito Bullet Time mudou o cinema para sempre." },
        { nomeUsuario: "Neo", textoComentario: "Keanu Reeves é o Neo perfeito. Um ícone da cultura pop." },
        { nomeUsuario: "FilosofiaCyberpunk", textoComentario: "O que é real? O filme te faz questionar a própria realidade." },
        { nomeUsuario: "PrimeiroFilme", textoComentario: "O primeiro é incomparável. Pura ficção científica de alta qualidade." },
    ],
    cowboy_bebop: [
        { nomeUsuario: "JazzEspacial", textoComentario: "A trilha sonora é o melhor que o anime tem a oferecer. Pura vibe." },
        { nomeUsuario: "SpikeSpiegel", textoComentario: "Spike é o protagonista mais *cool* dos animes. Estilo único." },
        { nomeUsuario: "SessionEnd", textoComentario: "Um final agridoce, mas poeticamente perfeito. See you Space Cowboy..." },
        { nomeUsuario: "Watanabe", textoComentario: "Cada episódio é um mini-filme com um gênero diferente. Genial." },
        { nomeUsuario: "FayeValentine", textoComentario: "Faye é uma personagem complexa e divertida. A química com Spike é ótima." },
    ],
    interestelar: [
        { nomeUsuario: "NolanEspacial", textoComentario: "Visualmente espetacular! O buraco negro Gargantua é lindo e assustador." },
        { nomeUsuario: "Teoria", textoComentario: "O filme de ficção científica mais complexo e emocional que existe. As teorias de relatividade são fascinantes." },
        { nomeUsuario: "Cooper", textoComentario: "A relação de Cooper e Murph é o coração do filme. A cena 'ficar' é emocionante." },
        { nomeUsuario: "TARS", textoComentario: "O robô TARS é um dos melhores alívios cômicos. 90% honestidade, 10% ironia." },
        { nomeUsuario: "Chorei", textoComentario: "A música do Hans Zimmer na cena do tesseract é de arrepiar." },
    ],
    de_volta_para_o_futuro: [
        { nomeUsuario: "DocBrown", textoComentario: "Um clássico atemporal que define o cinema dos anos 80. O DeLorean é um ícone." },
        { nomeUsuario: "MartyMcFly", textoComentario: "Marty McFly é o herói que todos amamos. Michael J. Fox é excelente." },
        { nomeUsuario: "MáquinadoTempo", textoComentario: "A melhor viagem no tempo do cinema. Divertido e cheio de regras que fazem sentido." },
        { nomeUsuario: "Trilogia", textoComentario: "A trilogia inteira é perfeita. Nenhum filme é ruim." },
        { nomeUsuario: "Nostalgia", textoComentario: "Assisto todo ano e nunca cansa. Pura magia." },
    ],
    westworld: [
        { nomeUsuario: "Robótica", textoComentario: "Uma série que explora a consciência artificial e a moralidade de forma profunda." },
        { nomeUsuario: "Dolores", textoComentario: "O arco da Dolores é complexo e surpreendente. A atriz é fantástica." },
        { nomeUsuario: "Labirinto", textoComentario: "Os mistérios de Westworld te prendem e te fazem teorizar a cada episódio." },
        { nomeUsuario: "HBOQualidade", textoComentario: "Produção caríssima e impecável. Visualmente deslumbrante." },
        { nomeUsuario: "PrimeiraTemporada", textoComentario: "A primeira temporada é uma obra-prima que redefiniu a ficção científica na TV." },
    ],
    stranger_things: [
        { nomeUsuario: "Anos80", textoComentario: "A nostalgia dos anos 80 é o que me conquistou. Referências incríveis." },
        { nomeUsuario: "Eleven", textoComentario: "Eleven é a personagem mais poderosa e cativante. Seus poderes são demais." },
        { nomeUsuario: "Vecna", textoComentario: "A quarta temporada elevou o nível do terror e o Vecna é um vilão assustador." },
        { nomeUsuario: "Aventura", textoComentario: "É basicamente um filme de Spielberg em formato de série. Pura aventura." },
        { nomeUsuario: "Hawkins", textoComentario: "O mistério do Mundo Invertido é a parte mais interessante da série." },
    ],
    rick_and_morty: [
        { nomeUsuario: "WubbaLubbaDubDub", textoComentario: "Humor ácido e ficção científica complexa. Genialidade pura!" },
        { nomeUsuario: "Rick", textoComentario: "Rick Sanchez é um gênio, mas também um personagem tragicômico. Profundo." },
        { nomeUsuario: "MelhorEpisódio", textoComentario: "O episódio do Picles Rick é lendário. Risada garantida." },
        { nomeUsuario: "Multiverso", textoComentario: "A exploração do multiverso é a parte mais divertida e caótica." },
        { nomeUsuario: "Filosofia", textoComentario: "Por trás da comédia, há sempre um toque de niilismo e existencialismo." },
    ],
    e_t_o_extraterrestre: [
        { nomeUsuario: "Spielberg", textoComentario: "Pura magia do cinema. A amizade entre Elliott e E.T. é tocante." },
        { nomeUsuario: "Infância", textoComentario: "Um filme que define a inocência e a maravilha da infância." },
        { nomeUsuario: "CenaClássica", textoComentario: "A cena da bicicleta voando contra a lua é icônica e atemporal." },
        { nomeUsuario: "ChoreiMuito", textoComentario: "O final sempre me emociona. Um filme sobre despedida e amizade." },
        { nomeUsuario: "E.T.", textoComentario: "O E.T. é o alienígena mais fofo e simpático do cinema." },
    ],
    donnie_darko: [
        { nomeUsuario: "Frank", textoComentario: "Um filme de culto obrigatório. Cuidado para não ter a mente explodida." },
        { nomeUsuario: "Coelho", textoComentario: "O coelho gigante é o visual mais perturbador do cinema adolescente." },
        { nomeUsuario: "Misterio", textoComentario: "Viagem no tempo, dimensões paralelas, e destino. Um quebra-cabeça." },
        { nomeUsuario: "Trilha", textoComentario: "A trilha sonora é perfeita e melancólica. Mad World no final é genial." },
        { nomeUsuario: "JakeGyllenhaal", textoComentario: "Jake Gyllenhaal na juventude, em uma performance brilhante." },
    ],
    neon_genesis_evangelion: [
        { nomeUsuario: "Shinji", textoComentario: "Um anime que te destrói psicologicamente. Complexo e visceral." },
        { nomeUsuario: "ReiAyanami", textoComentario: "Rei e Asuka são personagens que geram debates até hoje. Ótima construção." },
        { nomeUsuario: "Mechas", textoComentario: "Os Evas são incríveis, mas o foco é sempre o drama psicológico." },
        { nomeUsuario: "FinalConfuso", textoComentario: "O final da série é a definição de 'cult'. O End of Evangelion é essencial." },
        { nomeUsuario: "Animação", textoComentario: "A animação é datada, mas a direção de arte e os conceitos são atemporais." },
    ],
    steins_gate: [
        { nomeUsuario: "OkabeRintarou", textoComentario: "O melhor anime de viagem no tempo. O Rintarou é um protagonista carismático." },
        { nomeUsuario: "Kurisu", textoComentario: "A química entre Okabe e Kurisu é o coração da história. Shiina Mayuri é a paz." },
        { nomeUsuario: "MundoParalelo", textoComentario: "O conceito das 'Worldlines' é muito bem explorado. Tenso e emocionante." },
        { nomeUsuario: "Drama", textoComentario: "A primeira metade é comédia, a segunda é puro suspense e drama. Perfeita." },
        { nomeUsuario: "ElPsyCongroo", textoComentario: "Clássico moderno da ficção científica. Recomendação máxima." },
    ],
    dr_stone: [
        { nomeUsuario: "Senku", textoComentario: "Um shonen de ciência. Senku é um gênio divertido e inspirador." },
        { nomeUsuario: "1MilhãodeAnos", textoComentario: "A premissa de reconstruir a civilização do zero é fascinante." },
        { nomeUsuario: "Ciência", textoComentario: "Ensina muita coisa legal. A forma como eles constroem a tecnologia é viciante." },
        { nomeUsuario: "Taiju", textoComentario: "Taiju e Yuzuriha são o coração e o corpo do grupo. Lealdade pura." },
        { nomeUsuario: "AnimeEducativo", textoComentario: "É um dos animes mais originais e inteligentes da atualidade." },
    ],
    laboratorio_de_dexter: [
        { nomeUsuario: "DeeDee", textoComentario: "Dexter é um gênio, mas a Dee Dee é a rainha do caos. Adoro!" },
        { nomeUsuario: "NostalgiaCN", textoComentario: "Um dos pilares do Cartoon Network clássico. 'O que você está fazendo no meu laboratório?'" },
        { nomeUsuario: "Mandark", textoComentario: "O Mandark é um vilão cômico e a rivalidade é hilária." },
        { nomeUsuario: "Animação", textoComentario: "O traço e o estilo da animação são super distintos e engraçados." },
        { nomeUsuario: "EpisodiosCurtos", textoComentario: "Perfeito para assistir em blocos. Humor inteligente." },
    ],
    final_space: [
        { nomeUsuario: "Gary", textoComentario: "Humor nonsense e reviravoltas dramáticas. Gary é um protagonista cativante." },
        { nomeUsuario: "Mooncake", textoComentario: "O Mooncake é o bichinho mais fofo e destrutivo da galáxia. Chookity!" },
        { nomeUsuario: "LordCommander", textoComentario: "O Lord Commander é um vilão assustador e memorável." },
        { nomeUsuario: "Drama", textoComentario: "A série te faz rir muito, mas as partes dramáticas são surpreendentemente pesadas." },
        { nomeUsuario: "FicçãoSpace", textoComentario: "Uma aventura espacial épica com um coração enorme." },
    ],
    black_mirror: [
        { nomeUsuario: "Tecnologia", textoComentario: "Cada episódio te faz questionar o uso da tecnologia e seu impacto social." },
        { nomeUsuario: "Terror", textoComentario: "Não é terror, é o futuro. Alguns episódios são perturbadores de tão realistas." },
        { nomeUsuario: "Episodios", textoComentario: "'San Junipero' e 'USS Callister' são os meus favoritos. Pura arte." },
        { nomeUsuario: "NetflixOriginal", textoComentario: "Melhor série antológica de todos os tempos. Assisto a todos os novos." },
        { nomeUsuario: "Alerta", textoComentario: "Um aviso sobre onde a humanidade está indo. Essencial." },
    ],
    dark: [
        { nomeUsuario: "Winden", textoComentario: "O que é passado, o que é futuro? A série mais complexa da Netflix. Precisa de diagrama!" },
        { nomeUsuario: "Tempo", textoComentario: "Viagem no tempo e física quântica, tudo misturado com drama familiar. Genialidade alemã." },
        { nomeUsuario: "Jonas", textoComentario: "A jornada do Jonas te deixa tonto, mas é viciante. 'Sic Mundus Creatus Est'." },
        { nomeUsuario: "TrilhaSonora", textoComentario: "A música tema e a atmosfera sombria são perfeitas." },
        { nomeUsuario: "Amei", textoComentario: "Uma série que fecha todos os arcos de forma satisfatória no final. Raro!" },
    ],
    diarios_de_um_vampiro: [
        { nomeUsuario: "DamonSalvatore", textoComentario: "Equipe Damon sempre! O bad boy com coração de ouro." },
        { nomeUsuario: "ElenaGilbert", textoComentario: "Amei o triângulo amoroso e as reviravoltas sobrenaturais." },
        { nomeUsuario: "NostalgiaTeen", textoComentario: "A melhor série adolescente de vampiros. Clássico do CW." },
        { nomeUsuario: "Bruxas", textoComentario: "Os plots de bruxaria e outras criaturas são os mais legais da série." },
        { nomeUsuario: "Stefan", textoComentario: "Stefan é o bom moço, mas a química de Damon e Elena é inegável." },
    ],
    game_of_thrones: [
        { nomeUsuario: "WinterisComing", textoComentario: "A melhor série de fantasia já feita. O orçamento e a escala são gigantescos." },
        { nomeUsuario: "TyrionLannister", textoComentario: "O Tyrion é o personagem mais inteligente e carismático. Diálogos excelentes." },
        { nomeUsuario: "Batalhas", textoComentario: "As batalhas são épicas e realistas. Hardhome é uma das melhores." },
        { nomeUsuario: "ÚltimaTemporada", textoComentario: "O final foi decepcionante, mas as primeiras 6 temporadas são perfeitas." },
        { nomeUsuario: "Dragões", textoComentario: "Daenerys e seus dragões são o ápice da fantasia na TV." },
    ],
    the_witcher: [
        { nomeUsuario: "Geralt", textoComentario: "Henry Cavill nasceu para ser o Geralt. O 'Toss a Coin to your Witcher' gruda na cabeça." },
        { nomeUsuario: "Yennefer", textoComentario: "A Yennefer é uma das personagens mais fortes e interessantes da série." },
        { nomeUsuario: "Monstros", textoComentario: "Os efeitos especiais dos monstros e a coreografia de luta são excelentes." },
        { nomeUsuario: "Livros", textoComentario: "Recomendo os livros, mas a série faz um ótimo trabalho adaptando." },
        { nomeUsuario: "Jaskier", textoComentario: "O bardo Jaskier é a alma da comédia. Adoro ele." },
    ],

    naruto: [
        { nomeUsuario: "Clássico", textoComentario: "O início da jornada. O exame Chunin é o melhor arco! Sasuke e Naruto no telhado." },
        { nomeUsuario: "Time7", textoComentario: "A química do Time 7 na juventude é a melhor parte. Kakashi Sensei!" },
        { nomeUsuario: "RockLee", textoComentario: "A luta do Rock Lee contra o Gaara é uma das mais inspiradoras do shonen." },
        { nomeUsuario: "Nostalgia", textoComentario: "O anime que abriu as portas para muitos fãs de anime no ocidente." },
        { nomeUsuario: "Lutas", textoComentario: "As lutas são muito bem animadas e cheias de emoção." },
    ],
    naruto_the_last: [
        { nomeUsuario: "NaruHina", textoComentario: "Finalmente o casal se concretizou! O filme é lindo e focado no romance." },
        { nomeUsuario: "Canon", textoComentario: "O melhor filme da franquia Naruto, é essencial para a história." },
        { nomeUsuario: "Animação", textoComentario: "A animação está em outro nível, as cenas de ação são perfeitas." },
        { nomeUsuario: "Hinata", textoComentario: "A Hinata finalmente teve o destaque que merecia. Guerreira!" },
        { nomeUsuario: "Ootsutsuki", textoComentario: "O vilão Toneri é um desafio interessante e visualmente imponente." },
    ],
    attack_on_titan: [
        { nomeUsuario: "Titãs", textoComentario: "Um anime sombrio e complexo. O plot twist de que o mundo é maior é genial." },
        { nomeUsuario: "ErenYeager", textoComentario: "A transformação de Eren em vilão é um dos melhores arcos de anti-herói." },
        { nomeUsuario: "LeviAckerman", textoComentario: "Levi é o personagem mais badass. Sua luta contra o Titã Bestial é épica." },
        { nomeUsuario: "Muralhas", textoComentario: "A sensação de claustrofobia dentro das muralhas é aterrorizante." },
        { nomeUsuario: "AnimaçãoMAPPA", textoComentario: "O MAPPA fez um trabalho incrível na animação das batalhas do final." },
    ],
    black_clover: [
        { nomeUsuario: "Asta", textoComentario: "Nunca desistir! A energia do Asta é contagiante, mesmo que ele grite muito." },
        { nomeUsuario: "Yuno", textoComentario: "A rivalidade de Asta e Yuno é um shonen clássico. Os dois são incríveis." },
        { nomeUsuario: "Magia", textoComentario: "O sistema de magia é visualmente impressionante. Muita ação e feitiços." },
        { nomeUsuario: "Capitães", textoComentario: "Os Capitães dos Esquadrões são muito carismáticos e poderosos." },
        { nomeUsuario: "Fantasia", textoComentario: "Um shonen de fantasia que cumpre o que promete. Divertido e cheio de lutas." },
    ],
    dragon_ball_z: [
        { nomeUsuario: "Goku", textoComentario: "O anime que definiu uma geração. O Super Saiyajin é o momento mais icônico." },
        { nomeUsuario: "Vegeta", textoComentario: "Vegeta é o melhor personagem! A redenção dele é a mais emocionante." },
        { nomeUsuario: "Kamehameha", textoComentario: "As lutas são longas, mas a emoção e o poder são inegáveis." },
        { nomeUsuario: "SagaFreeza", textoComentario: "A Saga Freeza e Cell são os melhores arcos da série. Pura nostalgia." },
        { nomeUsuario: "AnimeLendário", textoComentario: "Um anime obrigatório para qualquer fã de ação." },
    ],
    hora_de_aventura: [
        { nomeUsuario: "FinnEJake", textoComentario: "Parece bobo, mas tem uma mitologia profunda e emocionante. Amo a Rainha Gelada!" },
        { nomeUsuario: "Nonsense", textoComentario: "O humor nonsense é genial. O BMO é o melhor console de videogame." },
        { nomeUsuario: "Marceline", textoComentario: "Marceline é a personagem mais *cool* e a história dela com Simon é linda." },
        { nomeUsuario: "FinalPerfeito", textoComentario: "O final da série é agridoce e muito bem executado. Arte pura." },
        { nomeUsuario: "DesenhoAdulto", textoComentario: "Um desenho que amadureceu junto com o público." },
    ],
    the_walking_dead: [
        { nomeUsuario: "RickGrimes", textoComentario: "A tensão da primeira temporada era insuperável. O medo dos zumbis era real." },
        { nomeUsuario: "Negan", textoComentario: "Negan é um vilão que amamos odiar. Jeffrey Dean Morgan é excelente." },
        { nomeUsuario: "Zumbis", textoComentario: "Melhor série de zumbis de todos os tempos. Drama humano e survival." },
        { nomeUsuario: "Gleen", textoComentario: "Algumas mortes são muito difíceis de superar, mas são essenciais para a história." },
        { nomeUsuario: "Sobrevivência", textoComentario: "A série te faz pensar: o que você faria para sobreviver?" },
    ],
    princess_mononoke: [
        { nomeUsuario: "Ghibli", textoComentario: "Hayao Miyazaki em sua melhor forma. Uma mensagem ecológica poderosa." },
        { nomeUsuario: "San", textoComentario: "San é uma personagem forte e complexa. A história é épica e emocionante." },
        { nomeUsuario: "Animação", textoComentario: "A animação é de tirar o fôlego. As criaturas e os espíritos são lindos." },
        { nomeUsuario: "Guerra", textoComentario: "A guerra entre a natureza e a humanidade é retratada de forma genial." },
        { nomeUsuario: "Clássico", textoComentario: "Um dos melhores filmes de animação de todos os tempos. Imperdível." },
    ],
    my_hero_academia: [
        { nomeUsuario: "Deku", textoComentario: "O desenvolvimento do Deku é inspirador. O 'Plus Ultra!' é contagiante." },
        { nomeUsuario: "AllMight", textoComentario: "All Might é o melhor mentor. A luta dele contra All For One é épica." },
        { nomeUsuario: "Quirks", textoComentario: "O sistema de poderes (Quirks) é muito criativo e divertido de ver." },
        { nomeUsuario: "Shonen", textoComentario: "Um shonen moderno que cumpre todos os clichês de forma excelente." },
        { nomeUsuario: "Batalhas", textoComentario: "As lutas são sempre dinâmicas e emocionantes. A animação é ótima." },
    ],
    demon_slayer_kimetsu_no_yaiba: [
        { nomeUsuario: "Tanjiro", textoComentario: "Animação da Ufotable é arte pura. As técnicas de respiração são lindas." },
        { nomeUsuario: "Nezuko", textoComentario: "Nezuko é a melhor irmã. A relação dela com Tanjiro é emocionante." },
        { nomeUsuario: "Muzan", textoComentario: "Muzan é um vilão assustador e elegante. Os Hashiras são incríveis." },
        { nomeUsuario: "Ação", textoComentario: "As cenas de ação são as mais fluidas e bem dirigidas que já vi." },
        { nomeUsuario: "Chorei", textoComentario: "A história é triste, mas a jornada dos irmãos é inspiradora. Um sucesso merecido." },
    ],
    la_casa_de_papel: [
        { nomeUsuario: "Professor", textoComentario: "O Professor é o gênio por trás de tudo. O planejamento é incrível." },
        { nomeUsuario: "Berlim", textoComentario: "Berlim é o personagem mais complexo e carismático. Adoro ele." },
        { nomeUsuario: "SérieNetflix", textoComentario: "Uma série de roubo e drama eletrizante. O tema é viciante." },
        { nomeUsuario: "BellaCiao", textoComentario: "A música tema virou um hino. A tensão das negociações é ótima." },
        { nomeUsuario: "Tokyo", textoComentario: "Tokyo é a narradora e o caos. A série é imperdível." },
    ],
    jujutsu_kaisen: [
        { nomeUsuario: "GojoSatoru", textoComentario: "Gojo é o personagem mais roubado e estiloso dos animes. A luta dele é épica." },
        { nomeUsuario: "YujiItadori", textoComentario: "Yuji é um protagonista gentil e determinado. O Sukuna é assustador." },
        { nomeUsuario: "Animação", textoComentario: "O estúdio MAPPA fez um trabalho espetacular. A animação das lutas é fluida." },
        { nomeUsuario: "ArcoShibuya", textoComentario: "O arco de Shibuya é um divisor de águas. Pesado e cheio de ação." },
        { nomeUsuario: "CursedEnergy", textoComentario: "O sistema de energia amaldiçoada é muito criativo. Excelente shonen." },
    ],
    fullmetal_alchemist_brotherhood: [
        { nomeUsuario: "Alquimia", textoComentario: "O melhor anime já feito. O conceito de Troca Equivalente é genial." },
        { nomeUsuario: "IrmãosElric", textoComentario: "A jornada de Edward e Alphonse para recuperar seus corpos é emocionante." },
        { nomeUsuario: "Vilões", textoComentario: "Os Homúnculos são vilões incríveis e complexos. O Father é assustador." },
        { nomeUsuario: "Roteiro", textoComentario: "Um roteiro sem pontas soltas. O final é perfeito e fecha todos os arcos." },
        { nomeUsuario: "MelhorAnime", textoComentario: "Uma obra-prima atemporal. Recomendação máxima para todos!" },
    ],
    mob_psycho_100: [
        { nomeUsuario: "Mob", textoComentario: "O desenvolvimento do Mob é incrível. Ele é um personagem puro e poderoso." },
        { nomeUsuario: "Reigen", textoComentario: "Reigen Arataka é o melhor charlatão. As cenas de comédia com ele são hilárias." },
        { nomeUsuario: "Animação", textoComentario: "A animação do Studio Bones é maluca e cheia de estilo. As lutas psíquicas são visuais." },
        { nomeUsuario: "Emocional", textoComentario: "Por trás da comédia, há uma mensagem linda sobre aceitação e emoções." },
        { nomeUsuario: "AnimeCurto", textoComentario: "Uma série curta e direta. Não tem filler, só pura qualidade." },
    ],
    esquadrao_suicida: [
        { nomeUsuario: "Arlequina", textoComentario: "Margot Robbie é a Arlequina perfeita. O estilo dela é impecável." },
        { nomeUsuario: "JamesGunn", textoComentario: "O filme do James Gunn é divertido, caótico e cheio de coração. Melhor que o primeiro." },
        { nomeUsuario: "BloodSport", textoComentario: "Idris Elba rouba a cena. Um líder complexo e divertido." },
        { nomeUsuario: "Ação", textoComentario: "Cenas de ação muito bem coreografadas e com um humor ácido." },
        { nomeUsuario: "Diversão", textoComentario: "Um filme de super-heróis que não se leva a sério e é muito divertido." },
    ],
    code_geass_lelouch_of_the_rebellion: [
        { nomeUsuario: "Lelouch", textoComentario: "Lelouch vi Britannia é um dos anti-heróis mais geniais dos animes. O Geass é incrível." },
        { nomeUsuario: "C.C.", textoComentario: "C.C. é a waifu de todos. O mistério dela e do Geass te prende." },
        { nomeUsuario: "Final", textoComentario: "O final (Zero Requiem) é um dos melhores e mais emocionantes de todos os animes. Perfeito!" },
        { nomeUsuario: "Estratégia", textoComentario: "As batalhas de estratégia e os mechas (Knightmares) são muito bem feitos." },
        { nomeUsuario: "AnimePolitico", textoComentario: "Um anime que mistura mechas, política e drama de forma excelente." },
    ],
    bleach: [
        { nomeUsuario: "Ichigo", textoComentario: "O anime que marcou o Big Three. O Bankai é um dos melhores power-ups." },
        { nomeUsuario: "SoulSociety", textoComentario: "O arco da Soul Society é o melhor da série. Tensão e reviravoltas." },
        { nomeUsuario: "Vilões", textoComentario: "Os Arrancars e o Aizen são vilões icônicos e assustadores." },
        { nomeUsuario: "Retorno", textoComentario: "A nova temporada (TYBW) está incrível. A animação está em outro nível." },
        { nomeUsuario: "Shinigami", textoComentario: "O conceito de Shinigami e Hollows é muito criativo. Ação e fantasia." },
    ],
    the_boys: [
        { nomeUsuario: "BillyButcher", textoComentario: "O Butcher é um anti-herói fascinante. A série é um soco no estômago." },
        { nomeUsuario: "Homelander", textoComentario: "O Homelander é o vilão mais assustador da TV. Um psicopata com capa." },
        { nomeUsuario: "Sátira", textoComentario: "Uma sátira genial e ácida ao mundo dos super-heróis e do capitalismo." },
        { nomeUsuario: "Vought", textoComentario: "A Vought é a corporação mais maligna. O roteiro é corajoso e sem limites." },
        { nomeUsuario: "Violência", textoComentario: "Violência explícita e cenas chocantes. Uma série que não poupa ninguém." },
    ],
    batman_a_serie_animada: [
        { nomeUsuario: "BruceTimm", textoComentario: "A melhor adaptação do Batman de todos os tempos. O design é atemporal." },
        { nomeUsuario: "Joker", textoComentario: "Mark Hamill é a voz do Coringa. Relação perfeita de dublagem e personagem." },
        { nomeUsuario: "Noir", textoComentario: "A atmosfera noir e o tom adulto do desenho são incríveis. Obra-prima." },
        { nomeUsuario: "HarleyQuinn", textoComentario: "A série que criou a Harley Quinn. Personagem icônica!" },
        { nomeUsuario: "Nostalgia", textoComentario: "Um desenho que amadureceu junto com o público. Clássico absoluto." },
    ],
    yu_yu_hakusho: [
        { nomeUsuario: "Kurama", textoComentario: "Um dos melhores animes de luta. O Torneio das Trevas é épico." },
        { nomeUsuario: "Yusuke", textoComentario: "Yusuke é um protagonista carismático e divertido. Seu Reigan é poderoso." },
        { nomeUsuario: "Vilões", textoComentario: "Os vilões são memoráveis (Toguro!). O anime é cheio de ação e humor." },
        { nomeUsuario: "Togashi", textoComentario: "O mesmo criador de Hunter x Hunter. A qualidade da história é inegável." },
        { nomeUsuario: "Clássico", textoComentario: "Um dos animes mais queridos do Brasil. Lenda!" },
    ],
    as_meninas_superpoderosas: [
        { nomeUsuario: "Docinho", textoComentario: "Açúcar, Tempero e Tudo que há de Bom! Um desenho icônico da Cartoon Network." },
        { nomeUsuario: "Professor", textoComentario: "O Professor é o pai mais dedicado da TV. As meninas são super fofas." },
        { nomeUsuario: "MojoJojo", textoComentario: "O Mojo Jojo é o melhor vilão cômico. O plano dele sempre falha de forma hilária." },
        { nomeUsuario: "Nostalgia", textoComentario: "As lutas são super divertidas e a animação é cheia de estilo." },
        { nomeUsuario: "Florzinha", textoComentario: "Adoro a personalidade de cada uma. Florzinha, Lindinha e Docinho!" },
    ],
    samurai_jack: [
        { nomeUsuario: "Aku", textoComentario: "O visual e a direção de arte são incríveis. Um desenho cinematográfico." },
        { nomeUsuario: "Ação", textoComentario: "As cenas de luta são silenciosas e cheias de estilo. Pura coreografia." },
        { nomeUsuario: "GenndyTartakovsky", textoComentario: "O criador de Primal e Dexter. O estilo dele é único." },
        { nomeUsuario: "LongoCaminho", textoComentario: "A jornada do Jack para voltar ao passado é épica e cheia de melancolia." },
        { nomeUsuario: "Final", textoComentario: "A temporada final amadureceu a série e deu um final digno ao Jack." },
    ],
    pokemon: [
        { nomeUsuario: "Pikachu", textoComentario: "Aventura e amizade. O anime que nos ensinou sobre a importância de ter um sonho." },
        { nomeUsuario: "AshKetchum", textoComentario: "O Ash é um herói inspirador. A jornada dele nunca acaba." },
        { nomeUsuario: "Nostalgia", textoComentario: "A primeira temporada é a mais nostálgica. O filme do Mewtwo é épico." },
        { nomeUsuario: "GottaCatchThemAll", textoComentario: "Os jogos são bons, mas o anime marcou a infância de todos." },
        { nomeUsuario: "TeamRocket", textoComentario: "A Equipe Rocket é hilária. A cada episódio, um novo plano falho." },
    ],

    forrest_gump_o_contador_de_historias: [
        { nomeUsuario: "LifeIsABox", textoComentario: "Um filme que te faz rir e chorar. A história do Forrest é emocionante." },
        { nomeUsuario: "TomHanks", textoComentario: "Tom Hanks em sua melhor forma. Uma performance inesquecível." },
        { nomeUsuario: "Jenny", textoComentario: "A relação dele com a Jenny é o coração do filme. Uma história de amor agridoce." },
        { nomeUsuario: "História", textoComentario: "O filme passa por momentos importantes da história americana. Genial." },
        { nomeUsuario: "Clássico", textoComentario: "Um clássico obrigatório. Um filme sobre bondade e inocência." },
    ],
    clube_da_luta: [
        { nomeUsuario: "TylerDurden", textoComentario: "O filme que te faz questionar o consumismo e a sociedade. O twist final é épico." },
        { nomeUsuario: "MindFuck", textoComentario: "Um dos filmes mais inteligentes e perturbadores já feitos. Brad Pitt e Edward Norton estão demais." },
        { nomeUsuario: "Regras", textoComentario: "A primeira regra do Clube da Luta..." },
        { nomeUsuario: "Cult", textoComentario: "Um filme cult que é um soco no estômago. O final é inesquecível." },
        { nomeUsuario: "Filosofia", textoComentario: "A melhor crítica ao capitalismo e à vida moderna." },
    ],
    the_fragrant_flower: [
        { nomeUsuario: "Drama", textoComentario: "Uma história emocionante e tocante sobre a vida e a morte. Chorei muito!" },
        { nomeUsuario: "Poético", textoComentario: "Um filme com uma sensibilidade rara. As cenas são lindas e melancólicas." },
        { nomeUsuario: "Atuação", textoComentario: "A atriz principal é incrível. Uma performance sutil e poderosa." },
        { nomeUsuario: "Indie", textoComentario: "Um filme independente que merece mais reconhecimento. Descoberta." },
        { nomeUsuario: "Sentimental", textoComentario: "Uma história sobre luto e memória. Muito pessoal." },
    ],
    o_poderoso_chefao: [
        { nomeUsuario: "Corleone", textoComentario: "A maior obra-prima do cinema. O roteiro, a direção, as atuações... tudo é perfeito." },
        { nomeUsuario: "MarlonBrando", textoComentario: "Marlon Brando é o Don Corleone. Uma das maiores performances da história." },
        { nomeUsuario: "Michael", textoComentario: "A transformação de Michael Corleone é o coração do filme. De herói a vilão." },
        { nomeUsuario: "Mafia", textoComentario: "O filme que definiu o gênero de máfia. Impecável e atemporal." },
        { nomeUsuario: "Trilogia", textoComentario: "A primeira parte é incomparável. Clássico obrigatório." },
    ],
    violet_evergarden: [
        { nomeUsuario: "ChoreiMuito", textoComentario: "O anime mais lindo e triste que já vi. Cada episódio é uma carta de amor." },
        { nomeUsuario: "AnimaçãoKyoAni", textoComentario: "A animação do Kyoto Animation é impecável. A mais bela de todas." },
        { nomeUsuario: "Violet", textoComentario: "A jornada da Violet para entender o significado de 'Eu te amo' é emocionante." },
        { nomeUsuario: "Cartas", textoComentario: "As histórias dos clientes e as cartas que ela escreve são tocantes." },
        { nomeUsuario: "Drama", textoComentario: "Um anime sobre luto, guerra e redenção. Arte pura." },
    ],
    your_lie_in_april: [
        { nomeUsuario: "Kaori", textoComentario: "Preparem os lenços. A história de Kaori e Kousei é linda e trágica." },
        { nomeUsuario: "MúsicaClássica", textoComentario: "As performances musicais são emocionantes e muito bem animadas. Inspiração." },
        { nomeUsuario: "Drama", textoComentario: "Um anime que te faz amar a música e chorar a cada episódio. Pura emoção." },
        { nomeUsuario: "Kousei", textoComentario: "A superação do Kousei é inspiradora. Um anime sobre recomeços." },
        { nomeUsuario: "Final", textoComentario: "O final é doloroso, mas poético. Um dos melhores animes de drama." },
    ],
    a_lista_de_schindler: [
        { nomeUsuario: "História", textoComentario: "Um filme essencial para a humanidade. A história de Schindler é emocionante." },
        { nomeUsuario: "Spielberg", textoComentario: "Um dos filmes mais importantes de Spielberg. Cinema puro e doloroso." },
        { nomeUsuario: "P&B", textoComentario: "A fotografia em preto e branco acentua o drama e a seriedade do tema." },
        { nomeUsuario: "Chorei", textoComentario: "Um filme que te faz chorar e refletir sobre a maldade humana. Essencial." },
        { nomeUsuario: "LiamNeeson", textoComentario: "Liam Neeson em uma atuação poderosa e inesquecível." },
    ],
    orange: [
        { nomeUsuario: "Naho", textoComentario: "Uma história sobre arrependimento e a chance de mudar o passado. Toca a alma." },
        { nomeUsuario: "Kakeru", textoComentario: "O drama do Kakeru é pesado. A série aborda a depressão de forma sensível." },
        { nomeUsuario: "AnimeDrama", textoComentario: "Um dos animes mais emotivos e com uma mensagem linda sobre amizade." },
        { nomeUsuario: "Futuro", textoComentario: "A ideia de receber cartas do futuro é muito bem explorada." },
        { nomeUsuario: "Amei", textoComentario: "Um anime que te faz querer abraçar os personagens. Recomendação." },
    ],
    cidade_de_deus: [
        { nomeUsuario: "CinemaNacional", textoComentario: "O melhor filme brasileiro de todos os tempos. Forte, visceral e real." },
        { nomeUsuario: "Buscapé", textoComentario: "A narrativa do Buscapé e a ascensão do Zé Pequeno são brilhantes." },
        { nomeUsuario: "ZéPequeno", textoComentario: "Um dos vilões mais icônicos do cinema. O ator é excelente." },
        { nomeUsuario: "Direção", textoComentario: "A direção de Fernando Meirelles é inovadora e dinâmica. Clássico." },
        { nomeUsuario: "Favelas", textoComentario: "Um retrato chocante e necessário da realidade das favelas cariocas." },
    ],
    o_show_de_truman: [
        { nomeUsuario: "Truman", textoComentario: "O filme te faz questionar o que é real. A atuação de Jim Carrey é dramática." },
        { nomeUsuario: "Crítica", textoComentario: "Uma crítica genial à mídia e à cultura de reality shows. Visionário." },
        { nomeUsuario: "Final", textoComentario: "O final, quando ele encontra a porta, é um dos melhores do cinema." },
        { nomeUsuario: "Drama", textoComentario: "Um filme emocionante sobre liberdade e a busca pela verdade." },
        { nomeUsuario: "PeterWeir", textoComentario: "Direção impecável. Um filme que envelhece muito bem." },
    ],
    a_espera_de_um_milagre: [
        { nomeUsuario: "ChoreiMuito", textoComentario: "Um drama lindo e comovente. A atuação de Michael Clarke Duncan é inesquecível." },
        { nomeUsuario: "JohnCoffey", textoComentario: "John Coffey é um personagem que te faz refletir sobre a bondade e a injustiça." },
        { nomeUsuario: "StephenKing", textoComentario: "A melhor adaptação de um livro de Stephen King. É pura magia." },
        { nomeUsuario: "Esperança", textoComentario: "Um filme sobre esperança, fé e milagres. Toca a alma." },
        { nomeUsuario: "Clássico", textoComentario: "Um filme que você precisa assistir pelo menos uma vez na vida." },
    ],
    haikyu: [
        { nomeUsuario: "Karasuno", textoComentario: "O melhor anime de esporte. A emoção e a paixão pelo vôlei são contagiantes." },
        { nomeUsuario: "Hinata", textoComentario: "A jornada do Hinata para ser o 'Pequeno Gigante' é inspiradora. Pura energia!" },
        { nomeUsuario: "Kageyama", textoComentario: "A parceria de Hinata e Kageyama é a melhor do anime. Gênios do vôlei." },
        { nomeUsuario: "Animação", textoComentario: "As cenas de vôlei são muito dinâmicas e realistas. Você sente a emoção do jogo." },
        { nomeUsuario: "Team", textoComentario: "A importância do trabalho em equipe e da amizade é o coração do anime." },
    ],
    breaking_bad: [
        { nomeUsuario: "Heisenberg", textoComentario: "A transformação de Walter White é a melhor dos últimos tempos. De professor a chefão do tráfico." },
        { nomeUsuario: "WalterWhite", textoComentario: "Uma das melhores séries da história. Roteiro impecável e reviravoltas geniais." },
        { nomeUsuario: "JessePinkman", textoComentario: "Jesse Pinkman é o nosso coração na série. A relação dele com Walter é complexa." },
        { nomeUsuario: "Final", textoComentario: "O final é perfeito e fecha todos os arcos de forma satisfatória." },
        { nomeUsuario: "Drama", textoComentario: "Um drama de crime viciante. Difícil parar de assistir." },
    ],
    o_gambito_da_rainha: [
        { nomeUsuario: "BethHarmon", textoComentario: "Beth Harmon é uma personagem fascinante. O drama dela é envolvente." },
        { nomeUsuario: "Xadrez", textoComentario: "O filme que fez o xadrez virar moda. As cenas de jogo são emocionantes." },
        { nomeUsuario: "Visual", textoComentario: "A direção de arte e os figurinos são deslumbrantes. Pura estética." },
        { nomeUsuario: "Netflix", textoComentario: "Uma das melhores minisséries da Netflix. Perfeita para maratonar." },
        { nomeUsuario: "Atuação", textoComentario: "Anya Taylor-Joy está incrível. Uma performance sutil e poderosa." },
    ],
    the_crown: [
        { nomeUsuario: "Realeza", textoComentario: "Uma visão fascinante e detalhada da vida da Rainha Elizabeth II e da família real." },
        { nomeUsuario: "História", textoComentario: "O filme te faz entender a complexidade da monarquia e da história britânica." },
        { nomeUsuario: "Produção", textoComentario: "A produção é luxuosa e impecável. Os atores são incríveis." },
        { nomeUsuario: "Drama", textoComentario: "Drama político e familiar viciante. A cada temporada, uma nova era." },
        { nomeUsuario: "Rainha", textoComentario: "A atuação das atrizes que interpretam a Rainha é perfeita. Impecável." },
    ],
    house_of_cards: [
        { nomeUsuario: "FrankUnderwood", textoComentario: "Frank Underwood é o vilão mais carismático da TV. O que ele fala para a câmera é genial." },
        { nomeUsuario: "Política", textoComentario: "Um drama político sombrio e viciante. Os bastidores do poder." },
        { nomeUsuario: "ClaireUnderwood", textoComentario: "Claire Underwood é a Lady Macbeth moderna. Uma personagem forte e ambiciosa." },
        { nomeUsuario: "Netflix", textoComentario: "Uma das primeiras grandes séries da Netflix. Qualidade de cinema." },
        { nomeUsuario: "Intriga", textoComentario: "Cheio de intrigas, traições e reviravoltas. Tensão do início ao fim." },
    ],
    grey_s_anatomy: [
        { nomeUsuario: "MeredithGrey", textoComentario: "A série de drama médico mais longa e viciante da história. Meredith é a melhor!" },
        { nomeUsuario: "DerekShepherd", textoComentario: "O amor de Meredith e Derek é o coração da série. O Dr. Shepherd é um ícone." },
        { nomeUsuario: "DramaMedico", textoComentario: "Casos médicos emocionantes e muito drama pessoal. Chorei muito." },
        { nomeUsuario: "Amizade", textoComentario: "A amizade de Meredith e Cristina Yang é a melhor da série. Pura cumplicidade." },
        { nomeUsuario: "SérieLonga", textoComentario: "Uma série que te prende por anos. Difícil parar de assistir." },
    ],
    euphoria: [
        { nomeUsuario: "Rue", textoComentario: "Uma série com uma estética visual única. A Zendaya está incrível no papel de Rue." },
        { nomeUsuario: "Adolescência", textoComentario: "Um retrato cru e honesto da adolescência moderna, com seus dramas e vícios." },
        { nomeUsuario: "Visual", textoComentario: "A fotografia, a trilha sonora e os figurinos são perfeitos. Pura arte." },
        { nomeUsuario: "Polêmica", textoComentario: "Uma série polêmica e necessária. Aborda temas difíceis com coragem." },
        { nomeUsuario: "HBO", textoComentario: "Qualidade de produção da HBO. O roteiro é ousado e complexo." },
    ],
    titanic: [
        { nomeUsuario: "JackERose", textoComentario: "A história de amor mais épica e trágica do cinema. Chorei muito!" },
        { nomeUsuario: "Cameron", textoComentario: "James Cameron em sua melhor forma. O resgate do naufrágio é impressionante." },
        { nomeUsuario: "Romance", textoComentario: "Um filme que mistura drama, romance e desastre de forma perfeita." },
        { nomeUsuario: "MyHeartWillGoOn", textoComentario: "A música da Celine Dion é um hino. O filme é um clássico atemporal." },
        { nomeUsuario: "CenaClássica", textoComentario: "A cena do beijo na proa do navio é a mais icônica do romance." },
    ],

    o_grande_hotel_budapeste: [
        { nomeUsuario: "WesAnderson", textoComentario: "A estética do Wes Anderson é inconfundível. Cores e simetria perfeitas." },
        { nomeUsuario: "Comédia", textoComentario: "Um filme engraçado, charmoso e cheio de personagens excêntricos." },
        { nomeUsuario: "RalphFiennes", textoComentario: "Ralph Fiennes está hilário como o concierge Gustave." },
        { nomeUsuario: "Visual", textoComentario: "O design de produção e os detalhes são incríveis. É um deleite visual." },
        { nomeUsuario: "Aventura", textoComentario: "Uma aventura divertida e cheia de reviravoltas. Clássico moderno." },
    ],
    friends: [
        { nomeUsuario: "Sitcom", textoComentario: "A melhor *sitcom* de todos os tempos. Impossível não rir das piadas." },
        { nomeUsuario: "RossERachel", textoComentario: "O casal mais amado e brigão da TV. 'We were on a break!'" },
        { nomeUsuario: "Nostalgia", textoComentario: "Assisto todo ano. O Central Perk e os amigos são o meu lugar feliz." },
        { nomeUsuario: "ChandlerBing", textoComentario: "Chandler Bing é o melhor personagem. Ironia e sarcasmo puros." },
        { nomeUsuario: "Final", textoComentario: "Um final emocionante e satisfatório. A série é perfeita." },
    ],
    irmao_do_jorel: [
        { nomeUsuario: "Brasil", textoComentario: "Melhor animação brasileira! As referências e o humor são muito nossos." },
        { nomeUsuario: "VóJuju", textoComentario: "Vó Juju é a melhor personagem. Seus conselhos e seu abraço de urso são incríveis." },
        { nomeUsuario: "Jorel", textoComentario: "O mistério do Jorel é o que me prende. O protagonista é o irmão sem nome." },
        { nomeUsuario: "Nostalgia", textoComentario: "Humor inocente e nostálgico. O desenho é genial e divertido." },
        { nomeUsuario: "CartoonBR", textoComentario: "Orgulho do Cartoon Network Brasil. Humor de qualidade." },
    ],
    titio_avo: [
        { nomeUsuario: "GoodMorning", textoComentario: "O desenho mais estranho e nonsense da história. Amo!" },
        { nomeUsuario: "Ganso", textoComentario: "O Ganso é o personagem mais divertido. O humor é absurdo e hilário." },
        { nomeUsuario: "TioAvô", textoComentario: "Titio Avô é o melhor. Ele sempre tem uma solução maluca para os problemas." },
        { nomeUsuario: "Humor", textoComentario: "Um desenho que não se leva a sério. Risada garantida." },
        { nomeUsuario: "Estranho", textoComentario: "O estranho é o que o torna bom. Pura criatividade." },
    ],
    spy_x_family: [
        { nomeUsuario: "AnyaForger", textoComentario: "A Anya é a personagem mais fofa e engraçada dos animes. 'Waku waku!'." },
        { nomeUsuario: "LoidYor", textoComentario: "O casal Loid e Yor é perfeito. O drama de espionagem e assassinato misturado com família." },
        { nomeUsuario: "Comédia", textoComentario: "Um anime de comédia e ação que cumpre o que promete. Divertido e emocionante." },
        { nomeUsuario: "Família", textoComentario: "A família Forger é a mais disfuncional e adorável. O Bond é o melhor cachorro." },
        { nomeUsuario: "AnimePopular", textoComentario: "Um dos animes mais populares da atualidade. Sucesso merecido." },
    ],
    the_office_us: [
        { nomeUsuario: "MichaelScott", textoComentario: "O melhor chefe da história das *sitcoms*. O humor é seco e constrangedor." },
        { nomeUsuario: "JimAndPam", textoComentario: "O romance de Jim e Pam é o coração da série. O *mockumentary* é genial." },
        { nomeUsuario: "DwightSchrute", textoComentario: "Dwight é o melhor personagem. Totalmente maluco e dedicado." },
        { nomeUsuario: "Comédia", textoComentario: "Uma série que te faz rir até doer a barriga. Humor inteligente." },
        { nomeUsuario: "MelhorSerie", textoComentario: "Assisto todo ano e nunca cansa. Clássico da comédia." },
    ],
    one_punch_man: [
        { nomeUsuario: "Saitama", textoComentario: "Saitama é o herói mais forte e entediado. Um soco resolve tudo." },
        { nomeUsuario: "Genos", textoComentario: "Genos é o discípulo mais dedicado. A relação deles é hilária." },
        { nomeUsuario: "Animação", textoComentario: "As lutas são épicas e a animação é de alta qualidade. O humor é genial." },
        { nomeUsuario: "Heróis", textoComentario: "A crítica à sociedade de super-heróis é muito inteligente." },
        { nomeUsuario: "Comédia", textoComentario: "Um shonen de comédia e ação que inverte os clichês de forma divertida." },
    ],
    kaguya_sama_love_is_war: [
        { nomeUsuario: "Kaguya", textoComentario: "A batalha de intelectos entre Kaguya e Miyuki é a coisa mais engraçada do mundo." },
        { nomeUsuario: "ComédiaRomântica", textoComentario: "O melhor anime de comédia romântica. O humor é inteligente e o romance é fofo." },
        { nomeUsuario: "Chika", textoComentario: "Chika Fujiwara é o caos. A dança dela no final é icônica." },
        { nomeUsuario: "Miyuki", textoComentario: "Miyuki Shirogane é o presidente mais esforçado. Quase perfeito." },
        { nomeUsuario: "AnimeEscola", textoComentario: "Um anime de escola que subverte os clichês. Recomendação máxima." },
    ],
    clarencio_o_otimista: [
        { nomeUsuario: "Clarencio", textoComentario: "Clarencio é o personagem mais otimista e feliz da TV. Pura energia!" },
        { nomeUsuario: "Nostalgia", textoComentario: "Um desenho divertido e inocente. A infância é retratada de forma linda." },
        { nomeUsuario: "Jeff", textoComentario: "O Jeff e o Sumo são os melhores amigos. A química do trio é ótima." },
        { nomeUsuario: "Humor", textoComentario: "Um desenho simples, mas com um humor genuíno e engraçado." },
        { nomeUsuario: "Cartoon", textoComentario: "Um desenho subestimado do Cartoon Network. Merece mais reconhecimento." },
    ],
    apenas_um_show: [
        { nomeUsuario: "MordecaiERigby", textoComentario: "O caos e as aventuras malucas. 'Ooooooohh!' é a marca registrada." },
        { nomeUsuario: "Nonsense", textoComentario: "Um desenho que mistura o cotidiano com o surreal de forma hilária." },
        { nomeUsuario: "Musica", textoComentario: "A trilha sonora e as referências musicais são incríveis." },
        { nomeUsuario: "JovensAdultos", textoComentario: "Um desenho que aborda a vida adulta de forma divertida." },
        { nomeUsuario: "Final", textoComentario: "O final da série é emocionante e fecha os arcos de forma satisfatória." },
    ],
    os_simpsons: [
        { nomeUsuario: "Homer", textoComentario: "A família amarela mais famosa da TV. Homer Simpson é um ícone." },
        { nomeUsuario: "Clássico", textoComentario: "Uma série que marcou gerações. O humor é atemporal e as piadas são geniais." },
        { nomeUsuario: "Anos90", textoComentario: "As primeiras 10 temporadas são a melhor parte. Nostalgia pura." },
        { nomeUsuario: "Previsões", textoComentario: "O desenho que previu o futuro. Assustador e engraçado." },
        { nomeUsuario: "HumorSocial", textoComentario: "Uma crítica social e política sutil e inteligente. Clássico absoluto." },
    ],
    family_guy: [
        { nomeUsuario: "SethMacFarlane", textoComentario: "Humor ácido e sem limites. As piadas são politicamente incorretas e hilárias." },
        { nomeUsuario: "Stewie", textoComentario: "Stewie e Brian são a melhor dupla. As aventuras deles são as mais engraçadas." },
        { nomeUsuario: "Cortes", textoComentario: "Os *cutaways* (cortes rápidos) são a marca registrada. Humor nonsense." },
        { nomeUsuario: "PeterGriffin", textoComentario: "Peter Griffin é o pai mais irresponsável e divertido da TV." },
        { nomeUsuario: "Comédia", textoComentario: "Uma série que te faz rir de tudo. Perfeito para quem gosta de humor negro." },
    ],
    south_park: [
        { nomeUsuario: "EricCartman", textoComentario: "O desenho mais satírico e crítico da TV. Cartman é o vilão mais divertido." },
        { nomeUsuario: "CríticaSocial", textoComentario: "Aborda temas polêmicos com humor ácido e inteligente. Genial." },
        { nomeUsuario: "Kenny", textoComentario: "Kenny morre em todo episódio. A piada nunca envelhece." },
        { nomeUsuario: "Atemporal", textoComentario: "Um desenho que se mantém relevante por décadas. Humor atemporal." },
        { nomeUsuario: "MelhorSerie", textoComentario: "A série mais inteligente e engraçada da comédia." },
    ],
    o_incrivel_mundo_de_gumball: [
        { nomeUsuario: "Gumball", textoComentario: "O desenho mais criativo e visualmente único da Cartoon Network." },
        { nomeUsuario: "Humor", textoComentario: "Humor meta e cheio de referências. O desenho é genial e divertido." },
        { nomeUsuario: "Familia", textoComentario: "A família Watterson é a mais maluca e adorável da TV. Animação criativa." },
        { nomeUsuario: "Nostalgia", textoComentario: "Um desenho que marcou a infância da nova geração. Clássico moderno." },
        { nomeUsuario: "Darwin", textoComentario: "Darwin é o melhor amigo. A amizade dele com Gumball é linda." },
    ],
    bob_esponja_calca_quadrada: [
        { nomeUsuario: "BikiniBottom", textoComentario: "O melhor desenho animado. As piadas e os personagens são icônicos." },
        { nomeUsuario: "Patrick", textoComentario: "Patrick Estrela é o melhor amigo e o mais burro. As frases dele são lendárias." },
        { nomeUsuario: "LulaMolusco", textoComentario: "Lula Molusco é o personagem mais sarcástico e divertido. Humor de qualidade." },
        { nomeUsuario: "Nostalgia", textoComentario: "Assisto desde criança e nunca cansa. Desenho atemporal." },
        { nomeUsuario: "Gary", textoComentario: "O caracol Gary é o animal de estimação mais fofo e inteligente. Meow." },
    ],
    du_dudu_e_edu: [
        { nomeUsuario: "Ed", textoComentario: "O desenho mais engraçado e nostálgico. Os planos deles são sempre malucos." },
        { nomeUsuario: "Dudu", textoComentario: "O Dudu é o cérebro da operação. O humor é simples e hilário." },
        { nomeUsuario: "TrêsMarias", textoComentario: "As Irmãs Kanker são as vilãs mais temidas. O final é sempre caótico." },
        { nomeUsuario: "Nostalgia", textoComentario: "Um clássico da Cartoon Network. O humor é atemporal e divertido." },
        { nomeUsuario: "Jardim", textoComentario: "O cenário do beco e as aventuras no bairro são o charme do desenho." },
    ],
    pica_pau: [
        { nomeUsuario: "Clássico", textoComentario: "O desenho mais antigo e engraçado. O Pica-Pau é o rei da bagunça." },
        { nomeUsuario: "Nostalgia", textoComentario: "As primeiras temporadas são as melhores. O humor é inocente e divertido." },
        { nomeUsuario: "Vilões", textoComentario: "O Zeca Urubu e o Leôncio são vilões cômicos e memoráveis." },
        { nomeUsuario: "Desenho", textoComentario: "Um desenho que marcou a infância de todos. Clássico da animação." },
        { nomeUsuario: "Risada", textoComentario: "A risada do Pica-Pau é a mais icônica. Impossível não rir." },
    ],
    tom_e_jerry: [
        { nomeUsuario: "Tom", textoComentario: "A rivalidade mais divertida da animação. As cenas de perseguição são geniais." },
        { nomeUsuario: "Jerry", textoComentario: "Jerry é o rato mais esperto e Tom é o gato mais azarado. Clássico." },
        { nomeUsuario: "Mudo", textoComentario: "Um desenho que não precisa de palavras para ser engraçado. A música é perfeita." },
        { nomeUsuario: "Nostalgia", textoComentario: "Um clássico atemporal. Assisto desde criança e nunca cansa." },
        { nomeUsuario: "Animação", textoComentario: "A animação é fluida e os *gags* são hilários. Pura arte." },
    ],
    archer: [
        { nomeUsuario: "SterlingArcher", textoComentario: "Humor ácido, referências e espionagem. Archer é o espião mais irresponsável." },
        { nomeUsuario: "LanaKane", textoComentario: "Lana é a melhor personagem. Forte, inteligente e a voz da razão." },
        { nomeUsuario: "ComédiaAdulto", textoComentario: "Uma série de comédia adulta que não tem medo de ser politicamente incorreta." },
        { nomeUsuario: "Diálogos", textoComentario: "Os diálogos são rápidos e cheios de referências. Precisa de legenda." },
        { nomeUsuario: "Animacão", textoComentario: "O estilo de animação e os cenários são muito bonitos. Estética única." },
    ],
    brooklyn_nine_nine: [
        { nomeUsuario: "JakePeralta", textoComentario: "A *sitcom* mais fofa e engraçada da atualidade. O Jake é um crianção adorável." },
        { nomeUsuario: "CaptainHolt", textoComentario: "O Capitão Holt é o melhor personagem. Humor seco e a voz da seriedade." },
        { nomeUsuario: "NineNine", textoComentario: "A química do elenco é perfeita. O *heist* de Halloween é o melhor episódio." },
        { nomeUsuario: "Comédia", textoComentario: "Uma série que te faz rir e chorar. O coração da série é a amizade." },
        { nomeUsuario: "Representatividade", textoComentario: "Uma série que aborda temas importantes de forma sutil e divertida." },
    ],

    bojack_horseman: [
        { nomeUsuario: "Bojack", textoComentario: "Um drama sombrio e hilário. BoJack é um personagem complexo e trágico." },
        { nomeUsuario: "Diane", textoComentario: "A Diane é o coração da série. A crítica à fama e à depressão é genial." },
        { nomeUsuario: "Animação", textoComentario: "A animação é criativa e os *gags* são hilários. Por trás, um drama pesado." },
        { nomeUsuario: "Final", textoComentario: "O final é agridoce e realista. Uma das melhores séries já feitas." },
        { nomeUsuario: "Filosofia", textoComentario: "Um desenho que te faz refletir sobre o sentido da vida e o luto." },
    ],
    over_the_garden_wall: [
        { nomeUsuario: "Wirt", textoComentario: "Uma minissérie linda e assustadora. A estética *vintage* é perfeita." },
        { nomeUsuario: "Aventureiros", textoComentario: "A jornada de Wirt e Greg pela floresta é mágica e melancólica." },
        { nomeUsuario: "Mistério", textoComentario: "O mistério do Estranho e da Besta te prende do início ao fim." },
        { nomeUsuario: "Halloween", textoComentario: "Perfeito para assistir no Halloween. Atmosfera de conto de fadas sombrio." },
        { nomeUsuario: "Música", textoComentario: "A trilha sonora é linda e nostálgica. Um clássico moderno." },
    ],
    steven_universe: [
        { nomeUsuario: "Steven", textoComentario: "Um desenho fofo e com uma mensagem linda sobre amor e aceitação." },
        { nomeUsuario: "Gemas", textoComentario: "As Crystal Gems são incríveis. A fusão é a melhor parte." },
        { nomeUsuario: "Música", textoComentario: "As músicas são cativantes e emocionantes. A trilha sonora é perfeita." },
        { nomeUsuario: "Representatividade", textoComentario: "Um desenho que aborda a representatividade de forma sutil e natural." },
        { nomeUsuario: "Aventura", textoComentario: "Uma aventura espacial e emocional. O desenvolvimento do Steven é lindo." },
    ],
    noiva_cadaver: [
        { nomeUsuario: "TimBurton", textoComentario: "A estética gótica e a animação *stop-motion* são a marca do Tim Burton." },
        { nomeUsuario: "Emily", textoComentario: "Emily é a noiva cadáver mais fofa e triste. O drama dela é comovente." },
        { nomeUsuario: "Visual", textoComentario: "O design de produção e os personagens são incríveis. Arte pura." },
        { nomeUsuario: "Drama", textoComentario: "Um filme sobre amor, morte e a vida após a morte. Melancólico e lindo." },
        { nomeUsuario: "Musical", textoComentario: "As músicas são engraçadas e a história é envolvente. Clássico." },
    ],
    o_silencio_dos_inocentes: [
        { nomeUsuario: "HannibalLecter", textoComentario: "Um dos melhores filmes de suspense psicológico. Hannibal Lecter é um vilão icônico." },
        { nomeUsuario: "JodieFoster", textoComentario: "Jodie Foster e Anthony Hopkins estão impecáveis. Atuações lendárias." },
        { nomeUsuario: "Suspense", textoComentario: "Um filme tenso e cheio de mistério. O suspense é construído de forma magistral." },
        { nomeUsuario: "Oscar", textoComentario: "Um dos poucos filmes a ganhar os 5 prêmios principais. Obra-prima." },
        { nomeUsuario: "Clássico", textoComentario: "Um clássico obrigatório. Um filme que te prende do início ao fim." },
    ],
    anabelle: [
        { nomeUsuario: "Boneca", textoComentario: "A boneca é assustadora e o filme é cheio de *jumpscares*. Terror de qualidade." },
        { nomeUsuario: "InvocaçãoDoMal", textoComentario: "O universo de Invocação do Mal é o melhor do terror moderno. A tensão é ótima." },
        { nomeUsuario: "Susto", textoComentario: "Um filme que te faz pular da cadeira. O terror é bem construído." },
        { nomeUsuario: "História", textoComentario: "A história de origem da boneca é interessante e assustadora." },
        { nomeUsuario: "Medo", textoComentario: "Um filme que te deixa com medo de bonecas. Recomendo para quem gosta de terror." },
    ],
    chainsaw_man: [
        { nomeUsuario: "Denji", textoComentario: "Denji é um protagonista caótico e divertido. A premissa é bizarra e genial." },
        { nomeUsuario: "Pochita", textoComentario: "Pochita é o cachorro/motosserra mais fofo e poderoso. Fofo!" },
        { nomeUsuario: "AnimaçãoMAPPA", textoComentario: "A animação do MAPPA é insana. As cenas de luta são viscerais e sangrentas." },
        { nomeUsuario: "Makima", textoComentario: "Makima é uma personagem misteriosa e assustadora. O plot twist é ótimo." },
        { nomeUsuario: "AnimeTerror", textoComentario: "Um anime de terror e ação que subverte os clichês. Único e viciante." },
    ],
    bastardos_inglorios: [
        { nomeUsuario: "Tarantino", textoComentario: "Tarantino reescrevendo a história. Diálogos geniais e cenas de ação estilizadas." },
        { nomeUsuario: "HansLanda", textoComentario: "Christoph Waltz é o melhor vilão de todos. O Coronel Landa é assustador e carismático." },
        { nomeUsuario: "Guerra", textoComentario: "Um filme de guerra que não é um filme de guerra. Pura diversão e tensão." },
        { nomeUsuario: "MelhorCena", textoComentario: "A cena inicial na fazenda é a mais tensa e bem dirigida do filme." },
        { nomeUsuario: "Cult", textoComentario: "Um filme cult obrigatório. Um clássico moderno." },
    ],
    dahmer_um_canibal_americano: [
        { nomeUsuario: "Assustador", textoComentario: "Uma série pesada e perturbadora. A atuação do Evan Peters é incrível." },
        { nomeUsuario: "TrueCrime", textoComentario: "Uma série *true crime* que retrata a vida de Jeffrey Dahmer. Fiel aos fatos." },
        { nomeUsuario: "Netflix", textoComentario: "Uma das séries mais assistidas da Netflix. Polêmica e viciante." },
        { nomeUsuario: "Drama", textoComentario: "Um drama de terror psicológico que te deixa tenso do início ao fim." },
        { nomeUsuario: "Amei", textoComentario: "Uma série chocante e necessária. Aborda o tema com seriedade." },
    ],
    the_handmaids_tale: [
        { nomeUsuario: "Gilead", textoComentario: "Uma série distópica e assustadora. O mundo de Gilead é opressor e realista." },
        { nomeUsuario: "June", textoComentario: "Elizabeth Moss é a June. Uma personagem forte e resiliente. O drama é intenso." },
        { nomeUsuario: "Feminismo", textoComentario: "Uma série que aborda o feminismo e a opressão feminina. Necessária." },
        { nomeUsuario: "Drama", textoComentario: "Um drama que te faz refletir sobre a liberdade e a tirania. Excelente." },
        { nomeUsuario: "Produção", textoComentario: "A fotografia e os figurinos são impressionantes. Qualidade HBO." },
    ],
    supernatural: [
        { nomeUsuario: "SamEDean", textoComentario: "A jornada dos irmãos Winchester é épica. O melhor *bromance* da TV." },
        { nomeUsuario: "Castiel", textoComentario: "Castiel é o melhor anjo. A amizade dele com Dean é o coração da série." },
        { nomeUsuario: "Caçadores", textoComentario: "A série que nos ensinou sobre monstros, demônios e anjos. Fantasia e terror." },
        { nomeUsuario: "Longa", textoComentario: "Uma série que durou 15 temporadas. Um clássico cult." },
        { nomeUsuario: "Nostalgia", textoComentario: "Assisto desde criança. O Impala e a trilha sonora de rock são o charme." },
    ],
    a_viagem_de_chihiro: [
        { nomeUsuario: "Miyazaki", textoComentario: "Uma obra-prima do Studio Ghibli. A imaginação do Miyazaki é genial." },
        { nomeUsuario: "Chihiro", textoComentario: "Chihiro é uma protagonista corajosa e determinada. A jornada é mágica." },
        { nomeUsuario: "Animação", textoComentario: "A animação é de tirar o fôlego. Os espíritos e as criaturas são lindos." },
        { nomeUsuario: "SemFace", textoComentario: "O Sem Rosto é o personagem mais misterioso e fofo. Adoro ele." },
        { nomeUsuario: "Clássico", textoComentario: "Um dos melhores filmes de animação de todos os tempos. Impecável." },
    ],
    invocacao_do_mal: [
        { nomeUsuario: "EdELorraine", textoComentario: "A melhor franquia de terror. O casal Warren é a alma dos filmes." },
        { nomeUsuario: "Terror", textoComentario: "Um filme que usa o terror psicológico e o *jump scare* de forma excelente." },
        { nomeUsuario: "HistóriaReal", textoComentario: "O fato de ser baseado em histórias reais torna tudo mais assustador." },
        { nomeUsuario: "Atmosfera", textoComentario: "A atmosfera de suspense e o medo são construídos de forma magistral." },
        { nomeUsuario: "Franquia", textoComentario: "O universo de Invocação do Mal é o melhor do terror moderno." },
    ],
    re_zero_starting_life_in_another_world: [
        { nomeUsuario: "Subaru", textoComentario: "O drama do Subaru é intenso. O retorno da morte é um conceito genial." },
        { nomeUsuario: "Emilia", textoComentario: "Emilia é a personagem mais gentil. O drama de Subaru e Rem é o coração." },
        { nomeUsuario: "Isekai", textoComentario: "Um *isekai* que subverte os clichês. A história é sombria e complexa." },
        { nomeUsuario: "Drama", textoComentario: "Um anime de drama e fantasia que te faz sofrer junto com o protagonista." },
        { nomeUsuario: "Anime", textoComentario: "Um dos melhores animes de fantasia e drama da atualidade. Viciante." },
    ],
};

export async function seedComentarios(prisma) {
    console.log("Iniciando o seeding de Comentários...");

    // REMOVA A PARTE DO streamMap se você só precisa dos IDs dos comentários

    let comentariosInseridos = 0;

    // Removemos a verificação "if (!streamId)"
    for (const slug in COMENTARIOS_POR_FILME) { 
        // Não precisamos mais do streamId para o Comentário, apenas do slug!
        
        const comentarios = COMENTARIOS_POR_FILME[slug];
        
        for (const comentario of comentarios) {
            await prisma.comentario.create({
                data: {
                    textoComentario: comentario.textoComentario,
                    nomeUsuario: comentario.nomeUsuario,
                    // O campo idFilmeCard é o slug que vem do seu array
                    idFilmeCard: slug, 
                },
            });
            comentariosInseridos++;
        }
    }

    console.log(`Seeding de Comentários concluído! Total de ${comentariosInseridos} comentários inseridos.`);
}